In [1]:
import coremltools as ct
import numpy as np
import PIL.Image
import cv2

In [2]:
model = ct.models.MLModel('./best_model_image.mlmodel')

In [3]:
# Print input description to get input shape.
print(model.get_spec().description.input)

[name: "input_1"
type {
  imageType {
    width: 320
    height: 240
    colorSpace: RGB
  }
}
]


In [52]:
# Scenario 1: load an image from disk.
def load_image(path, resize_to=None):
    # resize_to: (Width, Height)
    img = PIL.Image.open(path)
    img = img.convert('RGB')
    img_np = np.array(img) #.astype(np.float32)
    img_np = (img_np - 127.5) / 127.5
    return img_np, img

In [53]:
img_np, img = load_image('./data/standing_3.png')
print(img.mode)
print(img.size)

RGB
(320, 240)


In [54]:
print(img_np)

[[[-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]
  ...
  [-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]]

 [[-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]
  ...
  [-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]]

 [[-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]
  ...
  [-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]]

 ...

 [[-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]
  ...
  [-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]]

 [[-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]
  ...
  [-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]]

 [[-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]
  ...
  [-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]]]


In [59]:
PIL_image = PIL.Image.fromarray(img_np)

TypeError: Cannot handle this data type: (1, 1, 3), <f8

In [56]:
print(PIL_image.mode)

RGB


In [57]:
#img = cv2.imread("./data/head_right_6.png", 1)
out_dict = model.predict({'input_1': PIL_image})

In [58]:
print(out_dict)

{'313': array([[ -16.635796, -149.97414 ,  185.04688 , -243.99336 ]],
      dtype=float32)}
