In [153]:
import coremltools as ct
import numpy as np
import PIL.Image
import cv2
import torchvision.transforms as T
import torch

In [154]:
def get_transform():
    mean = 127.5
    std = 127.5
    normalize = T.Normalize(mean=mean, std=std)
    return T.Compose([normalize])

In [155]:
model = ct.models.MLModel('./best_model_tensor.mlmodel')

In [156]:
# Print input description to get input shape.
print(model.get_spec().description.input)

[name: "input_1"
type {
  multiArrayType {
    shape: 1
    shape: 3
    shape: 240
    shape: 320
    dataType: FLOAT32
  }
}
]


In [157]:
model_expected_input_shape = (1, 3, 240, 320)

In [158]:
def load_image_as_tensor(path):
    img = cv2.imread(path)
    img = torch.from_numpy(img)
    img = img.permute(2, 0, 1)
    img = img.unsqueeze(0)
    img = img.float()
    img = get_transform()(img)
    img = img.numpy()
    return img

In [174]:
img_as_tensor = load_image_as_tensor('./data/standing_3.png')

In [175]:
print(img_as_tensor)

[[[[-1. -1. -1. ... -1. -1. -1.]
   [-1. -1. -1. ... -1. -1. -1.]
   [-1. -1. -1. ... -1. -1. -1.]
   ...
   [-1. -1. -1. ... -1. -1. -1.]
   [-1. -1. -1. ... -1. -1. -1.]
   [-1. -1. -1. ... -1. -1. -1.]]

  [[-1. -1. -1. ... -1. -1. -1.]
   [-1. -1. -1. ... -1. -1. -1.]
   [-1. -1. -1. ... -1. -1. -1.]
   ...
   [-1. -1. -1. ... -1. -1. -1.]
   [-1. -1. -1. ... -1. -1. -1.]
   [-1. -1. -1. ... -1. -1. -1.]]

  [[-1. -1. -1. ... -1. -1. -1.]
   [-1. -1. -1. ... -1. -1. -1.]
   [-1. -1. -1. ... -1. -1. -1.]
   ...
   [-1. -1. -1. ... -1. -1. -1.]
   [-1. -1. -1. ... -1. -1. -1.]
   [-1. -1. -1. ... -1. -1. -1.]]]]


In [176]:
print(img_as_tensor.shape)

(1, 3, 240, 320)


In [177]:
out_dict = model.predict({'input_1': img_as_tensor})

In [178]:
print(out_dict)

{'313': array([[-5.475316  , -1.6567277 , -0.74248993,  4.363352  ]],
      dtype=float32)}
